### PR TITLE
Added isomorphic-fetch module

### PR DESCRIPTION
**Pull request by F-Ting**
fixed a bug where isomorphic-fetch was not included as a dev dependency, causing Mocha tests to not run.

### CODE REVIEW

**Comment by siefkenj** [comment]
I don't understand. Why has the indentation changed?

**Comment by F-Ting** [comment]
I'm not too sure myself, the indentation is correct on my local file before I pushed. I will close this pull request and findout why

**Comment by F-Ting** [comment]
I'm not too sure myself, the indentation is correct on my local file before I pushed. I will close this pull request and findout why

**Comment by F-Ting** [comment]
I'm not too sure myself, the indentation is correct on my local file before I pushed. I will close this pull request and findout why

**Pull request closed without merging**
