### PR TITLE
remove the "promise.reject" in the catch block

### PR DESCRIPTION
**Pull request by DarrenZhang01**

### CODE REVIEW

**Comment by siefkenj** [comment]
Are you sure this is the proper solution? Explain to me when Promise.reject should and shouldn't be used.

**Comment by DarrenZhang01** [comment]
@siefkenj In my understanding, reject is just a state in Promises. There is probably not one way of expressing "reject" state of a Promise in a "return Promise.reject()" way. If we use Promise.reject, usually we have a callback in the parenthesis. But in this case, we do not need it since the catch block already represents that this Promise is already rejected. Please correct me if there is anything I said wrong.

**Comment by siefkenj** [comment]
Read https://stackoverflow.com/questions/17293546/when-to-reject-resolve-a-promise and decide if reject is suitable or if there should be no return.

**Comment by siefkenj** [comment]
I don't see how `return false` makes any sense...

**Comment by DarrenZhang01** [comment]
It is better if we throw nothing and return nothing in this case in our catch block. And in this case, indeed all the tests pass without any handlePromiseRejection Error.

**Pull request merged**
